### ISSUE TITLE
Calibration action fails if calibration file does not have the correct existing fields

### ISSUE THREAD

**Issue by aromanielloNTIA** [NTIA/scos-actions#72]
We rely heavily on self-calibrations running on fielded sensors. Currently, the sensor and sigan calibration files must have the correct key structure already to store the results of a calibration. This means that calibrating a new set of parameters requires updating the calibration files.

The required nested key structure should be created automatically based on the parameters used in the Y-factor calibration, so that field calibrations can be performed and saved for parameter combinations not already present in the calibration files.

**Comment by aromanielloNTIA** [comment]
An example of the traceback when this problem is encountered (in this case, calibrating using a reference level which is not present in the calibration file):

``` bash
[2023-03-07 19:31:05,761] [DEBUG] Updating calibration at sample_rate = 14000000.0
[2023-03-07 19:31:05,761] [DEBUG] Updating calibration at frequency = 3555000000.0
[2023-03-07 19:31:05,761] [DEBUG] Updating calibration at reference_level = -20
[2023-03-07 19:31:05,761] [ERROR] action failed: -20
Traceback (most recent call last):
  File "/src/scheduler/scheduler.py", line 153, in _call_task_action
     detail = self.task.action_caller(schedule_entry_json, task_id)
  File "/usr/local/lib/python3.8/dist-packages/scos_actions/actions/calibrate_y_factor.py", line 212, in __call__
    detail += self.calibrate(p)
  File "/usr/local/lib/python3.8/dist-packages/scos_actions/actions/calibrate_y_factor.py", line 309, in calibrate
    sensor_calibration.update(
  File "/usr/local/lib/python3.8/dist-packages/scos_actions/calibration/calibration.py", line 54, in update
    cal_data = cal_data[value]
KeyError: -20
[2023-03-07 19:31:05,779] [INFO] all scheduled tasks completed

```
